[package]
name = "convert-to-svg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.52", features = ["derive"] }
colored = "3.0.0"
image = "0.25.9"
visioncortex = "0.8.9"
vtracer = "0.6.5"
